# syntax=docker/dockerfile:1
FROM python:3.12-slim

RUN pip install --no-cache-dir mlflow==3.4.0

EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:////mlflow/mlflow.db", \
     "--artifacts-destination", "/mlflow/artifacts", \
     "--serve-artifacts", \
     "--host", "0.0.0.0", \
     "--port", "5000"]
